version: '1.0.{build}'
image: Visual Studio 2019

#patch version in csproj file 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- cmd: >-
    dotnet restore geometry3Sharp\geometry3Sharp.csproj

    dotnet build geometry3Sharp\geometry3Sharp.csproj -c Release

    dotnet pack geometry3Sharp\geometry3Sharp.csproj -c Release

test_script:
- cmd: >-
   dotnet test --logger:Appveyor geometry3Sharp.Tests\geometry3Sharp.Tests.csproj -c Release

artifacts:
- path: geometry3Sharp\bin\Release\*.nupkg

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/gregmeess/index.json
  api_key:
    secure: KVBo3tq9evJxQe/+soJDrd83hVbby+2QSmDw0tEF1cnH7Laeoc1XbYiFLJu89WDb