name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build & test with dotnet
      run: dotnet test --configuration Release
    - name: Add GPR Source
      run: nuget sources Add -Name "GPR" -Source https://nuget.pkg.github.com/gregmeess/index.json -UserName gregmeess -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Packages
      run: nuget push nupkg\*.nupkg -Source "GPR" 
