name: Publish NuGet Package

on:
  push:
    tags: 
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create package
        run: dotnet pack geometry3Sharp/geometry3Sharp.csproj -c Release --include-source --include-symbols
      - name: Push package
        run: dotnet nuget push **/*.nupkg 
               --api-key ${{ secrets.NUGET_API_KEY }}
               --source https://api.nuget.org/v3/index.json