name: Publish NuGet Package

on:
  push:
    tags: 
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build project
        run: dotnet build -c Release
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1      
      - name: Create package
        run: dotnet pack -c Release --include-source
      - name: Push package
        run: |
          nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/gregmeess/index.json -Username gregmeess -Password ${{ secrets.GITHUB_TOKEN }}
          nuget push **\*.symbols.nupkg -source "GPR"
